[fmt]
line_length = 120
tab_width = 2
bracket_spacing = false
int_types = 'long'
multiline_func_header = 'params_first'
quote_style = 'single'
number_underscore = 'thousands'
wrap_comments = false

[profile.default]
solc = '0.8.19'
src = 'src'
test = 'src/test'
out = 'out'
libs = ['lib']
fuzz_runs = 1000
optimizer_runs = 10_000
block_timestamp = 1675855961

[profile.optimized]
via_ir = true
out = 'out-via-ir'
fuzz_runs = 5000

[profile.test]
via_ir = true
out = 'out-via-ir'
fuzz_runs = 5000
src = 'src/test'

[rpc_endpoints]
mainnet = "${OP_MAINNET_RPC}"
goerli = "${OP_GOERLI_RPC}"
