name: CI

on: [push]

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  lint:
    name: Run Linters
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Install dependencies
        run: yarn --frozen-lockfile --network-concurrency 1

      - run: yarn lint:check

  forge:
    name: Run Unit and E2E Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install forge dependencies
        run: forge install

      - name: Install yarn dependencies
        run: yarn install --frozen-lockfile

      - name: Precompile using 0.8.19 and via-ir=false
        run: yarn build

      - name: "Create env file"
        run: |
          touch .env
          echo OP_MAINNET_RPC="${{ secrets.OP_MAINNET_RPC }}" >> .env
          echo OP_GOERLI_RPC="${{ secrets.OP_GOERLI_RPC }}" >> .env
          echo OP_MAINNET_DEPLOYER_PK="${{ secrets.TEST_DEPLOYER_PK }}" >> .env
          echo OP_GOERLI_DEPLOYER_PK="${{ secrets.TEST_DEPLOYER_PK }}" >> .env
          cat .env

      - name: Run tests
        shell: bash
        run: yarn test

  # coverage:
  #   name: Run Coverage Tests
  #   runs-on: ubuntu-latest

  #   strategy:
  #     matrix:
  #       node-version: [16.x]

  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Use Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #         cache: "yarn"
  #     - name: Install Foundry
  #       uses: foundry-rs/foundry-toolchain@v1
  #       with:
  #         version: nightly
  #     - run: yarn install
  #     - run: yarn build
  #     - run: yarn coverage
  #     - uses: codecov/codecov-action@v3
  #       with:
  #         files: ./coverage/lcov.info
  #         flags: production
