name: CI

on: [push]

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  lint:
    name: Run Linters
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Install dependencies
        run: yarn --frozen-lockfile --network-concurrency 1

      - run: yarn lint:check

  forge:
    name: Run Unit and E2E Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install forge dependencies
        run: forge install

      - name: Install yarn dependencies
        run: yarn install --frozen-lockfile

      - name: Precompile using 0.8.20 and via-ir=false
        run: yarn build

      - name: "Create env file"
        run: |
          touch .env
          echo OP_MAINNET_RPC="${{ secrets.OP_MAINNET_RPC }}" >> .env
          echo OP_SEPOLIA_RPC="${{ secrets.OP_SEPOLIA_RPC }}" >> .env
          echo OP_MAINNET_DEPLOYER_PK="${{ secrets.TEST_DEPLOYER_PK }}" >> .env
          echo OP_SEPOLIA_DEPLOYER_PK="${{ secrets.TEST_DEPLOYER_PK }}" >> .env
          cat .env

      - name: Run tests
        shell: bash
        run: yarn test --nmc OnchainConfig